'use strict';

module.exports = {
    SUCCESS_CODE: 200,
    ALLREADY_EXIST: 409,
    ERROR_CODE: 400,
    AUTH_CODE: 401,

    //LOGIN LOGS
    DEFAULT_PASSWORD: '123456',

    WELCOME_USER_TEMPLATE_CODE: 'welcome',
    VERIFICATION_USER_TEMPLATE_CODE: 'verification',
    RESET_TEMPLATE_CODE: 'reset',
    INVITE_COMP_TEMPLATE_CODE_PUBLIC: 'inviteCompPublic',
    INVITE_COMP_TEMPLATE_CODE_PRIVATE: 'inviteCompPrivate',
    FORGOT_PASSWORD_CODE: 'forgot',
    CHANGE_PASSWORD_CODE: 'changepassword',
    SIGNIN_SUCCESS: 'Login successfully',
    NEW_USER_SAVE_SUCCESS: 'You registered successfully. Please check your mail and verify.',
    NEW_ROLE_SAVE_SUCCESS: 'New Role added successfully.',
    NEW_SPORT_SAVE_SUCCESS: 'New Sport added successsfully',
    NEW_ROUND_SAVE_SUCCESS: 'New Round added successsfully',
    NEW_CATEGORY_SAVE_SUCCESS: 'New Category added successfully.',
    NEW_TEAM_SAVE_SUCCESS: 'New Team added successfully',
    GAME_UPDATED_SUCCESS: 'Game detail updated successfully',
    ROUND_UPDATED_SUCCESS: 'Round detail updated successfully',
    // GAME_UPDATED_UNSUCCESS:'Game detail was unable to update',
    NEW_SUBCATEGORY_SAVE_SUCCESS: 'New subcategory added successfully',
    SOMETHING_WENT_WRONG: 'Something went wrong',
    SEND_MESSAGE_SUCCESS: 'Message sent successfully',
    EXT_ERROR: 'Please check the extension of file',
    DATA_NOT_FOUND: 'Data not found',
    DATA_FETCH_SUCCESS: 'Data fetched successfully',
    INVALID_LOGIN_DETAILS: 'Please enter correct email and password.',
    LOGIN_REQUIRED_FIELDS: 'Login credentials required',
    UNAUTHORIZE_USER: 'User is unauthorised',
    EMAIL_NOT_VERIFIED: 'Please verify your email.',
    INVALID_PASSWORD: 'Invalid Password',
    INVALID_TOKEN: 'Invalid Token',
    ADD_SUCCESS: 'Successfully added',
    INVITE_SUCCESS: 'Successfully invited',
    STATUS_CHANGE: 'Status changed successfully',
    EMAIL_ALREADY_REGISTERED: 'Email already registered. Please try another one',
    ROLE_EXIST: 'Role already exist',
    TEAM_EXIST: 'Team already exist',
    SPORT_EXIST: 'Sport already exist',
    BONUS_EXIST: 'Bonus already exist',
    ROUND_EXIST: 'Round already exist',
    COMPETITION_EXIST: 'Competition name already exist',
    COMPETITION_NOT_EXIST: 'Competition name not exist',
    GAME_STATE_UPDATED: 'Game state updated successfully',
    GAME_UPDATED_UNSUCCESS: 'Falied to update',
    DELETE_GAME_SUCCESS: 'game deleted successfully',
    GAME_EXIST: 'Game already exist',
    CATEGORY_EXIST: 'Category already exist',
    SUBCATEGORY_EXIST: 'Subcategory already exist',
    PASSWORD_RESET: 'Password Reset successfully',
    PASSWORD_CHANGE: 'Password changed successfully',
    SUCCESS_UPLOAD: 'Successfully Uploaded',
    UPLOAD_SAVED: 'Uploaded data saved successfully',
    EXT_ERROR: 'Error while uploading',
    UPLOAD_FAILED: 'Upload failed',
    NEW_COMP_SAVE_SUCCESS: 'New Competition added successfully',
    COMP_UPDATED_SUCCESS: 'Competition privacy status changed successfully',
    COMP_UPDATED_UNSUCCESS: 'Failed to change the privacy status',
    COMP_JOIN_SUCCESS: 'You have successfully joined the competition',
    PRODUCT_LIST_UNSUCCESS: 'Oops! Product list was not fetched',
    DELETE_ROUND_SUCCESS: 'Round deleted successfully',
    EMAILTEMPLATE_SAVE_SUCCESS: 'Email template saved successfully',
    NEW_BONUS_SAVE_SUCCESS: 'Bonus saved successfully',
    EMAIL_VERIFIED: 'Email verified successfully',
    INTERNAL_ERROR: 'Error occured',
    VERIFICATION_FAILED: 'Verification failed. PLease try again later.',
    PASSWORD_ERROR: 'Your old password is not correct.',
    TOKEN_ERROR: 'Token not found!',
    INVALID_TOKEN: 'Invalid Token!',
    NOT_PROPER_DATA: 'Not proper data!',
    USER_UPDATED_SUCCESS: 'User data updated successfully',
    USER_UPDATED_UNSUCCESS: 'User data was unable to be updated',
    LINK_SENT: 'Link sent successfully on mail to reset password',
    DELETE_USER_SUCCESS: 'User deleted successfully',
    DELETE_TEAM_SUCCESS: 'Team deleted successfully',
    USER_NOT_EXIST: 'User does not exist',
    DATA_FETCHED: 'Data fetched successfully',
    GAME_DATA_ADDED: 'Game data added successfully',
    PROFILE_PIC_SAVE: 'Profile pic saved',
    ERROR_OCCURED: 'Error Occured!',
    DELETE_CATEGORY_SUCCESS: 'Category deleted successfully',
    DELETE_SPORT_SUCCESS: 'Sport deleted successfully',
    SPORT_UPDATED_SUCCESS: 'Sportdetail updated successfully',
    SPORT_UPDATED_UNSUCCESS: 'Unable to update sportdetail',
    TEAM_UPDATED_SUCCESS: 'Teamdetail updated successfully',
    TEAM_UPDATED_UNSUCCESS: 'Unable to update teamdetail',
    DELETE_PRODUCT_SUCCESS: 'Delete product successfully',
    NOTIFICATION_SAVED: 'Notification data saved',
    NOTIFICATION_SENT_SUCCESS: 'Notification sent successfully',
    ASSOCIATED_CATEGORY: 'Category associated with product',
    SENT_VERIFICATION_LINK: 'Verification link sent to your mail',
    LOGO_IMG_PATH: './app/uploads/teamlogo/',
    PROFILE_IMG_PATH: './app/uploads/profile/',
    CHAT_IMG_PATH: './app/uploads/chat/',
    COVER_IMG_PATH: './app/uploads/cover/',
    AD_FILE_PATH: './app/uploads/ad/',
    DELETE_BONUS_SUCCESS: 'Bonus deleted successfully',

    DATA_SAVE_SUCCESS: 'Data save successfully',
    DATA_SAVE_USUCCESS: 'Failed to save',
    DATA_UPDATE_SUCCESS: 'Data updated successfully',
    DATA_UPDATE_UNSUCCESS: 'Failed to update',
    DATA_EXIST: 'Data already exist',
    DELETE_DATA_SUCCESS: 'Data deleted successfully',

    SAVE_TIPPING_SUCCESS: "Tips added successfully",

    ADD_SPORT_SUCCESSFULLY: "Sports Added Successfully",

    SEASON_EXIST: "Season already exist ",

    NEW_SEASON_SAVE_SUCCESSFuLLY: "New Season Created Successfully",

    DELETE_SEASON_SUCCESS: 'Season deleted successfully',

    PLEASE_ENTER_VALID_DATE: "Please Enter a Valid Date",

    ENTER_VALID_START_DATE: "Please Enter a Valid Start Date",

    SEASON_ALREADY_STARTDED: "Please season end after add a new season"

};